// src/lib/components/App.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import Terminal from '$lib/components/Terminal.svelte';

	let self: HTMLDivElement;

	let numColumns: number = 2;
	let terminalIndexes: number[] = [0, 1, 2];
	let terminals: Terminal[] = [];
	let activeTerminalIndex: number = NaN;
	let hoveredTerminalIndex: number = 0;

	type AppState = 'hovering' | 'active';
	let appState: AppState = 'active';

	onMount(async () => {
		self.focus();
		activateTerminal(hoveredTerminalIndex);
	});

	function handleKeyPress(event: KeyboardEvent): void {
		const key = event.key;
		const isShiftPressed = event.shiftKey;

		if (appState !== 'hovering') {
			return;
		}

		if (key === 'ArrowRight' || (key === 'Tab' && !isShiftPressed)) {
			event.preventDefault();
			hoverNext();
			return;
		}

		if (key === 'ArrowLeft' || (key === 'Tab' && isShiftPressed)) {
			event.preventDefault();
			hoverPrevious();
			return;
		}

		if (key === 'Enter' || key === 'Space') {
			activateTerminal(hoveredTerminalIndex);
		}
	}

	function hoverNext(): void {
		hoveredTerminalIndex = (hoveredTerminalIndex + 1) % terminalIndexes.length;
		hoverTerminalAt(hoveredTerminalIndex);
	}

	function hoverPrevious(): void {
		hoveredTerminalIndex =
			(hoveredTerminalIndex - 1 + terminalIndexes.length) % terminalIndexes.length;
		hoverTerminalAt(hoveredTerminalIndex);
	}

	function hoverTerminalAt(index: number) {
		if (!terminals[hoveredTerminalIndex]) {
			return;
		}

		terminals.forEach((_, i) => {
			if (i !== index) {
				terminals[i].unhover();
			}
		});

		terminals[hoveredTerminalIndex].hover();
	}

	function activateTerminal(index: number): void {
		if (terminals[index]) {
			terminals[index].unhover();
			terminals[index].activate();
			activeTerminalIndex = index;
			setAppState('active');
		}
	}

	function handleBlurred(event: CustomEvent): void {
		const { terminalIndex } = event.detail;
		self.focus();

		if (terminals[terminalIndex]) {
			terminals[terminalIndex].deactivate();
			terminals[terminalIndex].hover();
			hoveredTerminalIndex = terminalIndex;
			setAppState('hovering');
		}
	}

	function setAppState(state: AppState): void {
		if (state === 'hovering') activeTerminalIndex = NaN;
		if (state === 'active') hoveredTerminalIndex = NaN;
		appState = state;
	}
</script>

<div
	class="terminal-container"
	tabindex="0"
	bind:this={self}
	on:keydown={handleKeyPress}
	style="grid-template-columns: repeat({numColumns}, 1fr);"
>
	{#each terminalIndexes as terminalIndex}
		<Terminal {terminalIndex} bind:this={terminals[terminalIndex]} on:blurred={handleBlurred} />
	{/each}
</div>

<style>
	.terminal-container {
		background-color: #1c2128;
		padding: 0.6em;
		display: grid;
		gap: 0.6em;
		grid-auto-rows: 1fr;
		height: 100vh;
		box-sizing: border-box;
	}
</style>

// core/src/App.tsx
// src/App.tsx

import React, { useState, useEffect, useRef, KeyboardEvent } from 'react';
import Terminal, { TerminalHandle } from './components/Terminal';
import './App.css'; // Arquivo CSS para estilos

type AppState = 'hovering' | 'active';

const App: React.FC = () => {
  const selfRef = useRef<HTMLDivElement>(null);
  const [numColumns] = useState<number>(2);
  const terminalIndexes = [0, 1, 2];
  const terminalsRef = useRef<(TerminalHandle | null)[]>([]);
  const [activeTerminalIndex, setActiveTerminalIndex] = useState<number | null>(null);
  const [hoveredTerminalIndex, setHoveredTerminalIndex] = useState<number>(0);
  const [appState, setAppState] = useState<AppState>('active');

  useEffect(() => {
    selfRef.current?.focus();
    activateTerminal(hoveredTerminalIndex);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleKeyPress = (event: KeyboardEvent<HTMLDivElement>) => {
    const { key, shiftKey } = event;

    if (appState !== 'hovering') {
      return;
    }

    if (key === 'ArrowRight' || (key === 'Tab' && !shiftKey)) {
      event.preventDefault();
      hoverNext();
      return;
    }

    if (key === 'ArrowLeft' || (key === 'Tab' && shiftKey)) {
      event.preventDefault();
      hoverPrevious();
      return;
    }

    if (key === 'Enter' || key === ' ') {
      activateTerminal(hoveredTerminalIndex);
    }
  };

  const hoverNext = () => {
    const nextIndex = (hoveredTerminalIndex + 1) % terminalIndexes.length;
    setHoveredTerminalIndex(nextIndex);
    hoverTerminalAt(nextIndex);
  };

  const hoverPrevious = () => {
    const prevIndex =
      (hoveredTerminalIndex - 1 + terminalIndexes.length) % terminalIndexes.length;
    setHoveredTerminalIndex(prevIndex);
    hoverTerminalAt(prevIndex);
  };

  const hoverTerminalAt = (index: number) => {
    const terminal = terminalsRef.current[index];
    if (!terminal) return;

    terminalsRef.current.forEach((term, i) => {
      if (term && i !== index) {
        term.unhover();
      }
    });

    terminal.hover();
  };

  const activateTerminal = (index: number) => {
    const terminal = terminalsRef.current[index];
    if (terminal) {
      terminal.unhover();
      terminal.activate();
      setActiveTerminalIndex(index);
      setAppState('active');
    }
  };

  const handleBlurred = (index: number) => {
    selfRef.current?.focus();

    const terminal = terminalsRef.current[index];
    if (terminal) {
      terminal.deactivate();
      terminal.hover();
      setHoveredTerminalIndex(index);
      setAppState('hovering');
    }
  };

  return (
    <div
      className="terminal-container"
      tabIndex={0}
      ref={selfRef}
      onKeyDown={handleKeyPress}
      style={{ gridTemplateColumns: `repeat(${numColumns}, 1fr)` }}
    >
      {terminalIndexes.map((terminalIndex) => (
        <Terminal
          key={terminalIndex}
          terminalIndex={terminalIndex}
          ref={(el: TerminalHandle | null) => (terminalsRef.current[terminalIndex] = el)}
          onBlurred={handleBlurred}
        />
      ))}
    </div>
  );
};

export default App;
